name: p11_714220063
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: ^5.7.0
  timezone: ^0.10.0
  intl: ^0.20.1

flutter:
  uses-material-design: true
